# Generated by Django 4.2.7 on 2023-12-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=250, verbose_name='URL')),
                ('image', models.ImageField(upload_to='tattoos/tattoos/%Y/%m/%d', verbose_name='Изображение')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tattoos', to='gallery.style')),
            ],
            options={
                'verbose_name': 'Тату',
                'verbose_name_plural': 'Тату',
            },
        ),
        migrations.CreateModel(
            name='TattooProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Тату',
                'verbose_name_plural': 'Тату',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('gallery.tattoo',),
        ),
    ]
